# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Awminous Productions
email: gothicdork@gmail.com
description: Awminous Productions is a 2-person team of quirky artists named Arianne and Wesley. We love cartoons so we learned how to make them through drawing and animating.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://awminous.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_path: https://twitter.com/awminousprod
instagram_path: https://instagram.com/awminousprod
youtube_path: https://www.youtube.com/channel/UCiBER2y0mSd05wRD4OeKD2Q?
vimeo_path: https://vimeo.com/awminousprod
facebook_path: https:/facebook.com/awminousprod
github_path: https://github.com/awminousprod

# Build settings
permalink: pretty
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
